export default (req, res) => {
  const categories = [
    {
      id: 1,
      parentId: 0,
      name: "Cachorro",
      level: 1,
      position: 1,
      url: "cachorro",
      children: [
        {
          id: 11,
          parentId: 1,
          name: "Alimentação",
          level: 2,
          position: 1,
          url: "cachorro/alimentacao",
          children: [
            {
              id: 111,
              parentId: 11,
              name: "Ração",
              level: 3,
              position: 1,
              url: "cachorro/alimentacao/racao",
            },
            {
              id: 112,
              parentId: 11,
              name: "Petiscos e Ossinhos",
              level: 3,
              position: 2,
              url: "cachorro/alimentacao/petiscos",
            },
            {
              id: 113,
              parentId: 11,
              name: "Suplemento Alimentar",
              level: 3,
              position: 3,
              url: "cachorro/alimentacao/suplemento",
            },
            {
              id: 114,
              parentId: 11,
              name: "Comedouro e Bebedouro",
              level: 3,
              position: 4,
              url: "cachorro/alimentacao/suplemento",
            },
            {
              id: 115,
              parentId: 11,
              name: "Alimentação Natural",
              level: 3,
              position: 5,
              url: "cachorro/alimentacao/alimentacao-natural",
            },
          ],
        },
        {
          id: 12,
          parentId: 1,
          name: "Farmácia",
          level: 2,
          position: 2,
          url: "cachorro/farmacia",
        },
        {
          id: 13,
          parentId: 1,
          name: "Higiene",
          level: 2,
          position: 3,
          url: "cachorro/higiene",
        },
        {
          id: 14,
          parentId: 1,
          name: "Camas e Acessórios",
          level: 2,
          position: 4,
          url: "cachorro/acessorios",
        },
        {
          id: 15,
          parentId: 1,
          name: "Passeio",
          level: 2,
          position: 5,
          url: "cachorro/passeio",
        },
        {
          id: 16,
          parentId: 1,
          name: "Brinquedo",
          level: 2,
          position: 6,
          url: "cachorro/brinquedo",
        },
      ],
    },
    {
      id: 2,
      parentId: 0,
      name: "Gato",
      level: 1,
      position: 2,
      url: "gato",
      children: [
        {
          id: 22,
          parentId: 2,
          name: "Alimentação",
          level: 2,
          position: 1,
          url: "gato/alimentacao",
          children: [
            {
              id: 221,
              parentId: 22,
              name: "Ração",
              level: 3,
              position: 1,
              url: "gato/alimentacao/racao",
            },
            {
              id: 222,
              parentId: 22,
              name: "Petiscos e Ossinhos",
              level: 3,
              position: 2,
              url: "gato/alimentacao/petiscos",
            },
            {
              id: 223,
              parentId: 22,
              name: "Suplemento Alimentar",
              level: 3,
              position: 3,
              url: "gato/alimentacao/suplemento",
            },
            {
              id: 224,
              parentId: 22,
              name: "Comedouro e Bebedouro",
              level: 3,
              position: 4,
              url: "gato/alimentacao/suplemento",
            },
            {
              id: 225,
              parentId: 22,
              name: "Alimentação Natural",
              level: 3,
              position: 5,
              url: "gato/alimentacao/alimentacao-natural",
            },
          ],
        },
      ],
    },
    {
      id: 3,
      parentId: 0,
      name: "Outros Animais",
      level: 1,
      position: 3,
      url: "outros-animais",
      children: [
        {
          id: 33,
          parentId: 2,
          name: "Alimentação",
          level: 2,
          position: 1,
          url: "outros/alimentacao",
          children: [
            {
              id: 331,
              parentId: 33,
              name: "Ração",
              level: 3,
              position: 1,
              url: "outros/alimentacao/racao",
            },
            {
              id: 332,
              parentId: 33,
              name: "Petiscos e Ossinhos",
              level: 3,
              position: 2,
              url: "outros/alimentacao/petiscos",
            },
            {
              id: 333,
              parentId: 33,
              name: "Suplemento Alimentar",
              level: 3,
              position: 3,
              url: "outros/alimentacao/suplemento",
            },
            {
              id: 334,
              parentId: 33,
              name: "Comedouro e Bebedouro",
              level: 3,
              position: 4,
              url: "outros/alimentacao/suplemento",
            },
            {
              id: 335,
              parentId: 33,
              name: "Alimentação Natural",
              level: 3,
              position: 5,
              url: "outros/alimentacao/alimentacao-natural",
            },
          ],
        },
      ],
    },
    {
      id: 4,
      parentId: 0,
      name: "Serviços",
      level: 1,
      position: 4,
      url: "servicos",
      children: [
        {
          id: 41,
          parentId: 4,
          name: "Banho e Tosa",
          level: 2,
          position: 1,
          url: "servicos/banho-tosa",
        },
        {
          id: 42,
          parentId: 4,
          name: "Serviço Veterinário",
          level: 2,
          position: 2,
          url: "servicos/veterinario",
        },
        {
          id: 43,
          parentId: 4,
          name: "Serviço Veterinário",
          level: 2,
          position: 3,
          url: "servicos/veterinario",
        },
      ],
    },
    {
      id: 5,
      parentId: 0,
      name: "Principais Marcas",
      level: 1,
      position: 4,
      url: "marcas",
      children: [
        {
          id: 51,
          parentId: 5,
          name: "Royal Canin",
          level: 2,
          position: 1,
          url: "marcas/royal-canin",
        },
        {
          id: 52,
          parentId: 4,
          name: "Pedigree",
          level: 2,
          position: 2,
          url: "marcas/pedigree",
        },
      ],
    },
  ];

  res.statusCode = 200;
  res.json(categories);
};
